---
- name: Install Apache
  package:
    name: httpd
    state: present
  become: true

- name: Create vmX.html files with FQDN
  copy:
    content: "{{ ansible_fqdn }}"
    dest: "{{ playbook_dir }}/roles/webserver-HumberID/files/vm{{ item }}.html"
  delegate_to: localhost
  with_items: [1, 2, 3]

- name: Copy vmX.html files to nodes
  copy:
    src: "{{ playbook_dir }}/roles/webserver-HumberID/files/vm{{ item }}.html"
    dest: "/var/www/html/index.html"
    mode: '0444'
  with_items: [1, 2, 3]
  become: true

- name: Ensure Apache is started and enabled
  service:
    name: httpd
    state: started
    enabled: true
  become: true
