---
- name: Add group cloudadmins
  group:
    name: cloudadmins
    state: present
  become: true

- name: Add users and assign to groups
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
  with_items:
    - user100
    - user200
    - user300
  become: true

- name: Distribute SSH keys for users
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/home/' + item + '/.ssh/id_rsa.pub') }}"
  with_items:
    - user100
    - user200
    - user300
  become: true
