---
- name: Create /part1 partition
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
  become: true

- name: Mount /part1
  mount:
    path: /part1
    src: /dev/sdb1
    fstype: xfs
    state: mounted
  become: true

- name: Create /part2 partition
  filesystem:
    fstype: ext4
    dev: /dev/sdb2
  become: true

- name: Mount /part2
  mount:
    path: /part2
    src: /dev/sdb2
    fstype: ext4
    state: mounted
  become: true
